### ISSUE TITLE
Pytorch Dataloaders & Pinned Memory

### ISSUE THREAD

**Issue by LeanderK** [pesser/edflow#53]
I am thinking about using edflow but I have the problem that I have either very small datasets and models or multiple GPUs and reasonably small models with big batches. This makes the time spent training per batch real relativly small and the pin_memory argument to pytorch-datasets important. Here are the technical details what the difference is:
 - https://devblogs.nvidia.com/how-optimize-data-transfers-cuda-cc/

I think there's no possiblitiy to use the pytorch-dataloaders directly? I am not sure where the data-loading is actually happening.

EDIT: I don't think this ticket needs immediate attention.

**Comment by LeanderK** [comment]
If there is code that expects an iterator the pytorch data-loaders would fit right in

**Comment by pesser** [comment]
This will be difficult to achieve while remaining framework agnostic. You could adapt the make batches function https://github.com/pesser/edflow/blob/c6c73efa581fa1032ce7a02387c471483648de98/edflow/iterators/batches.py#L110
to check if the dataset is a pytorch dataset and if so return a pytorch dataloader. But then all functions working with the data must expect pytorch tensors instead of numpy arrays so I'd guess this breaks a lot of existing stuff.

The other option would be a hook that maintains pinned memory for the batch and copies the numpy inputs into it before running the model, i.e. some variant of https://github.com/pesser/edflow/blob/c6c73efa581fa1032ce7a02387c471483648de98/edflow/hooks/pytorch_hooks.py#L155
that uses pinned memory. But I'm honestly not sure if or under what conditions that brings a speedup because this will not run interleaved with the model's computation.

**Comment by pesser** [comment]
does anyone want to look into this? Otherwise I'll close for now since this would require some effort evaluating if and how this improves performance.
