### ISSUE TITLE
Conflicting behavior of edflow -e -p and eval_all

### ISSUE THREAD

**Issue by theRealSuperMario** [pesser/edflow#81]
1. `edflow -e -p` will get the latest checkpoint from the project and pass it to the evaluator.
https://github.com/pesser/edflow/blob/4871181eb08a4cc79e2e058e84be78a0737cb6b4/edflow/edflow#L130-L133

2. The evaluator will add a hook to restore the current model when provided with a checkpoint.
https://github.com/pesser/edflow/blob/4871181eb08a4cc79e2e058e84be78a0737cb6b4/edflow/iterators/tf_evaluator.py#L85-L91

3. When using `eval_all=True` and `eval_forever=True`, this will simply keep reloading the same checkpoint. This is not the desired behavior

This goes back to 293c86724775fe6c34c7b6db5e76cc2c5f131824.

Because one of our tests was wrong, we are discovering this problem afterwards (#80 )

I suggest to change the edflow behavior here
https://github.com/pesser/edflow/blob/4871181eb08a4cc79e2e058e84be78a0737cb6b4/edflow/edflow#L130-L133

back to 
```
if opt.checkpoint is not None:
    checkpoint = opt.checkpoint
else:
    checkpoint = None
```

This means that the last checkpoint needs to be provided by hand, if desired. We could introduce a `-c last` if we want, but that is to the future

**Comment by pesser** [comment]
I don't agree with the proposed fix. I think it is good default behavior to load the last checkpoint from the project if not told otherwise.
We should think about how to solve this. Currently, the framework agnostic part of edflow only knows about `eval_forever`: https://github.com/pesser/edflow/blob/4871181eb08a4cc79e2e058e84be78a0737cb6b4/edflow/main.py#L199
This only makes sense if we want to either

- evaluate all checkpoints
- wait for new checkpoints

so it definitely does not make sense in combination with `-c`. So why not change the logic in https://github.com/pesser/edflow/blob/4871181eb08a4cc79e2e058e84be78a0737cb6b4/edflow/iterators/tf_evaluator.py#L85-L91
also to

      if not config.get("eval_forever", False): 


This should work for now without changing the current behavior. With respect to a better solution for the future, I think all of this logic should become part of the framework agnostic edflow.

**Comment by pesser** [comment]
proposed solution: `-c` takes precedence and sets `eval_forever` and `eval_all` to `False` since this combination does not make sense

**Comment by pesser** [comment]
proposed solution: `-c` takes precedence and sets `eval_forever` and `eval_all` to `False` since this combination does not make sense
